# Generated by Django 2.2.5 on 2019-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empnew',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
